# Generated by Django 3.2.12 on 2022-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='User ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='User Name')),
                ('user_avatar', models.CharField(max_length=500, verbose_name='User Avatar')),
                ('user_language', models.CharField(max_length=5, verbose_name='User Language')),
                ('subscribed_to', models.CharField(max_length=20, verbose_name='Subscribed To')),
                ('subscription_status', models.CharField(max_length=20, verbose_name='Subscription Status')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.AddIndex(
            model_name='subscriberdb',
            index=models.Index(fields=['user_id'], name='main_subscr_user_id_569de8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberdb',
            index=models.Index(fields=['subscribed_to'], name='main_subscr_subscri_93bb34_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberdb',
            index=models.Index(fields=['subscription_status'], name='main_subscr_subscri_b05776_idx'),
        ),
    ]
