# Generated by Django 3.2.12 on 2022-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220216_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberdb',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='subscriberdb',
            index=models.Index(fields=['user_role'], name='main_subscr_user_ro_194143_idx'),
        ),
    ]
